# Generated by Django 5.1.1 on 2024-10-06 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='answer1',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='answer2',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='student_id',
        ),
    ]
