# Generated by Django 5.1.1 on 2024-10-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_answer_question_delete_sentence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.SmallAutoField(primary_key=True, serialize=False),
        ),
    ]
