# Generated by Django 5.1.1 on 2024-10-07 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_delete_answer_alter_question_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(default='000000000', max_length=9)),
                ('category', models.CharField(default='카테고리', max_length=1000)),
                ('question', models.CharField(default='질문', max_length=1000)),
                ('answer1', models.TextField(default='답변1')),
                ('answer2', models.TextField(default='답변2')),
                ('comment', models.TextField(default='진단')),
                ('grade', models.FloatField()),
                ('question_id', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='question', to='server.question')),
            ],
        ),
    ]
