# Generated by Django 5.1.1 on 2024-10-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='grade',
            field=models.FloatField(default=0),
        ),
    ]
