# Generated by Django 5.1.1 on 2024-10-07 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_alter_answer_question_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question_id',
        ),
    ]
