# Generated by Django 5.1.1 on 2024-10-07 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_remove_answer_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='answer', to='server.question'),
            preserve_default=False,
        ),
    ]
