# Generated by Django 5.1.1 on 2024-10-08 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_answer_question_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='category',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
    ]
