# Generated by Django 5.1.1 on 2024-10-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_remove_answer_category_remove_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer1',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer2',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='answer',
            name='comment',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='answer',
            name='grade',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='answer',
            name='student_id',
            field=models.CharField(default=None, max_length=9),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
