# Generated by Django 5.1.1 on 2024-10-08 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_alter_answer_answer1_alter_answer_answer2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='answer', to='server.question'),
        ),
    ]
